# Review of Basic Differential Geometry

Let's test a few things. Let $X\colon M \to TM$ be a vector field on a manifold $M$. 
We define $\Phi \colon \mathbb{R} \times M \to M$ by letting $\Phi(t,x) = \Phi_t(x)$ be 
the unique solution to $$\frac{d}{dt} \Phi_t(x) = X(\Phi_t(x)).$$
